### ISSUE TITLE
Why categorized in javascript?

### ISSUE THREAD

**Issue by ghaseminya** [Softmotions/ncms#64]
Hi
Why ncms not in java category in github search!?
Thanks

**Comment by adamansky** [comment]
Hi! Thanks. I've added the `javaee` keyword on ncms project  page.
I think it categorized as `javascript` by github due to source code language ratio:  
`JavaScript 57.3%	 Java 23.4%	 CSS 9.0%	 Kotlin 7.1%, ...`

**Comment by ghaseminya** [comment]
Can you change .gitignore file to change main dir for this problem?
